# .pipeline/config.yml
steps:
  mavenStaticCodeChecks: false
  npmExecuteLint: false
  cloudFoundryDeploy:
    apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
    cfOrg: 'depdev1'
    cfSpace: 'dev1'
    cfCredentialsId: 'cf'
  tmsUpload:
    tmsCredentialsId: 'tms-key'
    nodeName: 'dev1'

stages:
  Release:
    tmsUpload: true
    
    

