# .pipeline/config.yml
# .pipeline/config.yml
steps:
  cloudFoundryDeploy:
    cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com' # Apne subaccount se check karein
    cfOrg: 'dpeqa1'  # Apna Org name likhein
    cfSpace: 'dev1'          # Apna Space name likhein
    cfCredentialsId: 'cf'   # 
